FROM node:alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

#------------ PROD STAGE ------------#

FROM node:alpine

WORKDIR /app

COPY --from=build  /app/build .

CMD [] 
#TODO: 