FROM node:alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

#------------ PROD STAGE ------------#  

FROM node:alpine

RUN npm i -g serve

WORKDIR /app

COPY --from=build /app/build .

EXPOSE 3000

CMD ["serve", "-p", "3000", "-s", "."]